// <auto-generated />
using MAADISWEETS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaadiSweets.Migrations
{
    [DbContext(typeof(SweetAppDbContext))]
    [Migration("20190613194134_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MAADISWEETS.Models.Sweets", b =>
                {
                    b.Property<int>("SweetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SweetName");

                    b.HasKey("SweetId");

                    b.ToTable("Sweets");
                });
#pragma warning restore 612, 618
        }
    }
}
